
name: winx64
run-name: winx64 build
on: [push]
jobs:
  angle-win-x64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: create source dir
        shell: bash
        run: |
          mkdir $GITHUB_WORKSPACE/gnu
          mkdir $GITHUB_WORKSPACE/gnu/src
          mkdir $GITHUB_WORKSPACE/gnu/src/angle
          mkdir $GITHUB_WORKSPACE/gnu/src/angle/code
          mkdir $GITHUB_WORKSPACE/gnu/src/angle/depot
          
      - name: Download depot_tools
        shell: bash
        run: |
          echo $GITHUB_WORKSPACE
          ls -alr $GITHUB_WORKSPACE
          7z x $GITHUB_WORKSPACE/depot_tools.zip -o$GITHUB_WORKSPACE/gnu/src/angle/depot

      - name: list depot_tools
        shell: bash
        run: |
          ls -al D:/a/bangle/bangle/gnu/src/angle/depot
          
      - name: gclient init
        shell: cmd
        run: |
          set "PATH=D:\\a\\bangle\\bangle\\gnu\\src\angle\\depot;%PATH%"
          cd D:\\a\\bangle\\bangle\\gnu\\src\angle\\depot && gclient
     
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
  
      - name: pull code
        shell: cmd
        run: |
          set "PATH=D:\\a\\bangle\\bangle\\gnu\\src\angle\\depot;%PATH%"
          set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
          cd D:\\a\\bangle\\bangle\\gnu\\src\angle\\code && git clone --depth 1 -b main  https://github.com/google/angle.git
          
      - name: angle bootstrap
        shell: cmd
        run: |
          set "PATH=D:\\a\\bangle\\bangle\\gnu\\src\angle\\depot;%PATH%"
          set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
          cd D:\\a\\bangle\\bangle\\gnu\\src\angle\\code\\angle && python scripts\bootstrap.py
      
      - name: gclient sync
        shell: cmd
        run: |
          set "PATH=D:\\a\\bangle\\bangle\\gnu\\src\angle\\depot;%PATH%"
          set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
          cd D:\\a\\bangle\\bangle\\gnu\\src\angle\\code\\angle && gclient sync

      - name: compress
        shell: cmd
        run: |
          7z a -r -mx9 D:\\a\\bangle\\bangle\\gnu
        
      - name: publish
        uses: actions/upload-artifact@v3
        with:
            name: art
            path: D:\\a\\bangle\\bangle\\gnu.7z
