
name: winx64
run-name: winx64 build
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-2022
    steps:
      - name: create source dir
        shell: bash
        run: cd c:/ && mkdir src
      - name: pull code
        shell: bash
        run: cd c:/src && git pull https://github.com/google/angle
      - name: Download a file
        shell: bash
        run: curl https://storage.googleapis.com/chrome-infra/depot_tools.zip -o c:/tmp/
