
name: winx64
run-name: winx64 build
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-2022
    steps:
      - name: create source dir
        shell: bash
        run: |
          mkdir $HOME/gnu
          mkdir $HOME/gnu/src
          mkdir $HOME/gnu/src/angle
          mkdir $HOME/gnu/src/angle/depot
      - name: Download depot_tools
        shell: bash
        run: |
          curl https://storage.googleapis.com/chrome-infra/depot_tools.zip -o $HOME/gnu/src/angle/depot
          cd $HOME/gnu/src/angle/depot && 7z x .\depot_tools.zip
      - name: pull code
        uses: actions/checkout@v3
        with:
          repository: google/angle
          ref: refs/heads/main
          submodules: true

