
name: winx64
run-name: winx64 build
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: create source dir
        shell: bash
        run: |
          mkdir $GITHUB_WORKSPACE/gnu
          mkdir $GITHUB_WORKSPACE/gnu/src
          mkdir $GITHUB_WORKSPACE/gnu/src/angle
          mkdir $GITHUB_WORKSPACE/gnu/src/angle/code
          mkdir $GITHUB_WORKSPACE/gnu/src/angle/depot
      - name: Download depot_tools
        shell: bash
        run: |
          echo $GITHUB_WORKSPACE
          ls -alr $GITHUB_WORKSPACE
          7z x $GITHUB_WORKSPACE/depot_tools.zip -o$GITHUB_WORKSPACE/gnu/src/angle/depot
      - name: show depo
        shell: bash
        run: |
          ls -l $GITHUB_WORKSPACE/gnu/src/angle/depot 
      - name: publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: D:\a\bangle\bangle\gnu\*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
